Fail
file path is :
projects/deltachat-core/rust/src/contact.rs

output is:


error is :
   Compiling deltachat v1.139.6 (/home/k/ogs_PHD/LLM4SE/2Rust_projects/auto_get_functionPair/projects/deltachat-core/rust)
error[E0252]: the name `Result` is defined multiple times
  --> src/contact.rs:15:42
   |
5  | use anyhow::Result;
   |     -------------- previous import of the type `Result` here
...
15 | use anyhow::{bail, ensure, Context as _, Result};
   |                                          ^^^^^^ `Result` reimported here
   |
   = note: `Result` must be defined only once in the type namespace of this module

error[E0432]: unresolved import `crate::Context`
 --> src/contact.rs:6:5
  |
6 | use crate::Context;
  |     ^^^^^^^^^^^^^^ no `Context` in the root
  |
help: a similar name exists in the module
  |
6 | use crate::context;
  |            ~~~~~~~
help: consider importing one of these items instead
  |
6 | use anyhow::Context;
  |     ~~~~~~~~~~~~~~~
6 | use core::task::Context;
  |     ~~~~~~~~~~~~~~~~~~~
6 | use crate::context::Context;
  |     ~~~~~~~~~~~~~~~~~~~~~~~
6 | use exif::Context;
  |     ~~~~~~~~~~~~~
    and 2 other candidates

error[E0432]: unresolved import `crate::ContactId`
 --> src/contact.rs:7:5
  |
7 | use crate::ContactId;
  |     ^^^^^^^---------
  |     |      |
  |     |      help: a similar name exists in the module: `contact`
  |     no `ContactId` in the root

error[E0425]: cannot find value `DC_CONTEXT_MAGIC` in this scope
   --> src/contact.rs:614:31
    |
614 |     if context.inner.magic != DC_CONTEXT_MAGIC || id <= DC_CONTACT_ID_LAST_SPECIAL {
    |                               ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `DC_CONTACT_ID_LAST_SPECIAL` in this scope
   --> src/contact.rs:614:57
    |
614 |     if context.inner.magic != DC_CONTEXT_MAGIC || id <= DC_CONTACT_ID_LAST_SPECIAL {
    |                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `new_blocking` in this scope
   --> src/contact.rs:619:31
    |
619 |         && contact.blocked != new_blocking {
    |                               ^^^^^^^^^^^^ not found in this scope
...
657 | fn new_blocking() -> bool {
    |    ------------ an associated function by that name is available on `Self` here

error[E0425]: cannot find value `new_blocking` in this scope
   --> src/contact.rs:622:53
    |
622 |         sqlite3_bind_int(stmt.as_ref().unwrap(), 1, new_blocking)?;
    |                                                     ^^^^^^^^^^^^ not found in this scope
...
657 | fn new_blocking() -> bool {
    |    ------------ an associated function by that name is available on `Self` here

error[E0425]: cannot find value `SQLITE_DONE` in this scope
   --> src/contact.rs:624:52
    |
624 |         if sqlite3_step(stmt.as_ref().unwrap()) != SQLITE_DONE {
    |                                                    ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `new_blocking` in this scope
   --> src/contact.rs:631:53
    |
631 |         sqlite3_bind_int(stmt.as_ref().unwrap(), 1, new_blocking)?;
    |                                                     ^^^^^^^^^^^^ not found in this scope
...
657 | fn new_blocking() -> bool {
    |    ------------ an associated function by that name is available on `Self` here

error[E0425]: cannot find value `DC_CHAT_TYPE_SINGLE` in this scope
   --> src/contact.rs:632:53
    |
632 |         sqlite3_bind_int(stmt.as_ref().unwrap(), 2, DC_CHAT_TYPE_SINGLE)?;
    |                                                     ^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `SQLITE_DONE` in this scope
   --> src/contact.rs:634:52
    |
634 |         if sqlite3_step(stmt.as_ref().unwrap()) != SQLITE_DONE {
    |                                                    ^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `DC_EVENT_CONTACTS_CHANGED` in this scope
   --> src/contact.rs:644:49
    |
644 |         context.inner.cb(context.inner.clone(), DC_EVENT_CONTACTS_CHANGED, 0, 0);
    |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

warning: unused import: `std::sync::Arc`
 --> src/contact.rs:4:5
  |
4 | use std::sync::Arc;
  |     ^^^^^^^^^^^^^^
  |
note: the lint level is defined here
 --> src/lib.rs:6:5
  |
6 |     unused,
  |     ^^^^^^
  = note: `#[warn(unused_imports)]` implied by `#[warn(unused)]`

warning: unused import: `Result`
  --> src/contact.rs:15:42
   |
15 | use anyhow::{bail, ensure, Context as _, Result};
   |                                          ^^^^^^

error[E0425]: cannot find function `dc_contact_new` in this scope
   --> src/contact.rs:611:19
    |
611 |     let contact = dc_contact_new(&context.inner)?;
    |                   ^^^^^^^^^^^^^^ not found in this scope

error[E0609]: no field `magic` on type `Arc<InnerContext>`
   --> src/contact.rs:614:22
    |
614 |     if context.inner.magic != DC_CONTEXT_MAGIC || id <= DC_CONTACT_ID_LAST_SPECIAL {
    |                      ^^^^^ unknown field
    |
    = note: available fields are: `blobdir`, `sql`, `smeared_timestamp`, `generating_key_mutex`, `oauth2_mutex` ... and 17 others

error[E0425]: cannot find function `goto_cleanup` in this scope
   --> src/contact.rs:615:9
    |
615 |         goto_cleanup();
    |         ^^^^^^^^^^^^ not found in this scope
    |
help: consider using the associated function on `Self`
    |
615 |         Self::goto_cleanup();
    |         ++++++

error[E0425]: cannot find function `dc_contact_load_from_db` in this scope
   --> src/contact.rs:618:8
    |
618 |     if dc_contact_load_from_db(&contact, &context.inner.sql, id)?
    |        ^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `dc_sqlite3_prepare` in this scope
   --> src/contact.rs:621:21
    |
621 |         stmt = Some(dc_sqlite3_prepare(&context.inner.sql, "UPDATE contacts SET blocked=? WHERE id=?;")?);
    |                     ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `sqlite3_bind_int` in this scope
   --> src/contact.rs:622:9
    |
622 |         sqlite3_bind_int(stmt.as_ref().unwrap(), 1, new_blocking)?;
    |         ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `sqlite3_bind_int` in this scope
   --> src/contact.rs:623:9
    |
623 |         sqlite3_bind_int(stmt.as_ref().unwrap(), 2, id)?;
    |         ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `sqlite3_step` in this scope
   --> src/contact.rs:624:12
    |
624 |         if sqlite3_step(stmt.as_ref().unwrap()) != SQLITE_DONE {
    |            ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `goto_cleanup` in this scope
   --> src/contact.rs:625:13
    |
625 |             goto_cleanup();
    |             ^^^^^^^^^^^^ not found in this scope
    |
help: consider using the associated function on `Self`
    |
625 |             Self::goto_cleanup();
    |             ++++++

error[E0425]: cannot find function `sqlite3_finalize` in this scope
   --> src/contact.rs:627:9
    |
627 |         sqlite3_finalize(stmt.as_ref().unwrap())?;
    |         ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `dc_sqlite3_prepare` in this scope
   --> src/contact.rs:630:21
    |
630 | ...   stmt = Some(dc_sqlite3_prepare(&context.inner.sql, "UPDATE chats SET blocked=? WHERE type=? AND id IN (SELECT chat_id FROM chats_co...
    |                   ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `sqlite3_bind_int` in this scope
   --> src/contact.rs:631:9
    |
631 |         sqlite3_bind_int(stmt.as_ref().unwrap(), 1, new_blocking)?;
    |         ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `sqlite3_bind_int` in this scope
   --> src/contact.rs:632:9
    |
632 |         sqlite3_bind_int(stmt.as_ref().unwrap(), 2, DC_CHAT_TYPE_SINGLE)?;
    |         ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `sqlite3_bind_int` in this scope
   --> src/contact.rs:633:9
    |
633 |         sqlite3_bind_int(stmt.as_ref().unwrap(), 3, id)?;
    |         ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `sqlite3_step` in this scope
   --> src/contact.rs:634:12
    |
634 |         if sqlite3_step(stmt.as_ref().unwrap()) != SQLITE_DONE {
    |            ^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `goto_cleanup` in this scope
   --> src/contact.rs:635:13
    |
635 |             goto_cleanup();
    |             ^^^^^^^^^^^^ not found in this scope
    |
help: consider using the associated function on `Self`
    |
635 |             Self::goto_cleanup();
    |             ++++++

error[E0425]: cannot find function `dc_marknoticed_contact` in this scope
   --> src/contact.rs:638:9
    |
638 |         dc_marknoticed_contact(&context.inner, id)?;
    |         ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0599]: no method named `cb` found for struct `Arc<InnerContext>` in the current scope
   --> src/contact.rs:644:23
    |
644 |         context.inner.cb(context.inner.clone(), DC_EVENT_CONTACTS_CHANGED, 0, 0);
    |                       ^^ method not found in `Arc<InnerContext>`

error[E0425]: cannot find function `cleanup` in this scope
   --> src/contact.rs:647:5
    |
647 |     cleanup();
    |     ^^^^^^^ not found in this scope
    |
help: consider using the associated function on `Self`
    |
647 |     Self::cleanup();
    |     ++++++

error[E0425]: cannot find function `dc_contact_unref` in this scope
   --> src/contact.rs:648:5
    |
648 |     dc_contact_unref(&contact);
    |     ^^^^^^^^^^^^^^^^ not found in this scope

Some errors have detailed explanations: E0252, E0425, E0432, E0599, E0609.
For more information about an error, try `rustc --explain E0252`.
warning: `deltachat` (lib) generated 2 warnings
error: could not compile `deltachat` (lib) due to 32 previous errors; 2 warnings emitted
warning: build failed, waiting for other jobs to finish...
warning: `deltachat` (lib test) generated 2 warnings (2 duplicates)
error: could not compile `deltachat` (lib test) due to 32 previous errors; 2 warnings emitted
error: command `/home/k/.rustup/toolchains/1.77.1-x86_64-unknown-linux-gnu/bin/cargo test --no-run --message-format json-render-diagnostics` exited with code 101

