Fail
file path is :
projects/deltachat-core/rust/src/contact.rs

output is:


error is :
   Compiling deltachat v1.139.6 (/home/k/ogs_PHD/LLM4SE/2Rust_projects/auto_get_functionPair/projects/deltachat-core/rust)
error[E0252]: the name `Result` is defined multiple times
  --> src/contact.rs:13:42
   |
4  | use anyhow::Result;
   |     -------------- previous import of the type `Result` here
...
13 | use anyhow::{bail, ensure, Context as _, Result};
   |                                          ^^^^^^ `Result` reimported here
   |
   = note: `Result` must be defined only once in the type namespace of this module

error[E0252]: the name `ContactAddress` is defined multiple times
  --> src/contact.rs:19:5
   |
5  | use deltachat_contact_tools::{ContactAddress, VcardContact};
   |                               -------------- previous import of the type `ContactAddress` here
...
19 |     ContactAddress, VcardContact,
   |     ^^^^^^^^^^^^^^--
   |     |
   |     `ContactAddress` reimported here
   |     help: remove unnecessary import
   |
   = note: `ContactAddress` must be defined only once in the type namespace of this module

error[E0252]: the name `VcardContact` is defined multiple times
  --> src/contact.rs:19:21
   |
5  | use deltachat_contact_tools::{ContactAddress, VcardContact};
   |                                               ------------ previous import of the type `VcardContact` here
...
19 |     ContactAddress, VcardContact,
   |                     ^^^^^^^^^^^^-
   |                     |
   |                     `VcardContact` reimported here
   |                     help: remove unnecessary import
   |
   = note: `VcardContact` must be defined only once in the type namespace of this module

error[E0425]: cannot find value `DC_CONTEXT_MAGIC` in this scope
   --> src/contact.rs:612:57
    |
612 |     if context.is_null_or_invalid() || context.magic != DC_CONTEXT_MAGIC || id <= DC_CONTACT_ID_LAST_SPECIAL {
    |                                                         ^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `DC_CONTACT_ID_LAST_SPECIAL` in this scope
   --> src/contact.rs:612:83
    |
612 |     if context.is_null_or_invalid() || context.magic != DC_CONTEXT_MAGIC || id <= DC_CONTACT_ID_LAST_SPECIAL {
    |                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `new_blocking` in this scope
   --> src/contact.rs:616:81
    |
616 |     if dc_contact_load_from_db(contact, context.sql, id)? && contact.blocked != new_blocking {
    |                                                                                 ^^^^^^^^^^^^ not found in this scope
...
654 | fn new_blocking() -> i32 {
    |    ------------ an associated function by that name is available on `Self` here

error[E0425]: cannot find value `new_blocking` in this scope
   --> src/contact.rs:618:71
    |
618 |         stmt.as_mut().unwrap().bind(&[rusqlite::types::ToSql::to_sql(&new_blocking)?])?;
    |                                                                       ^^^^^^^^^^^^ not found in this scope
...
654 | fn new_blocking() -> i32 {
    |    ------------ an associated function by that name is available on `Self` here

error[E0433]: failed to resolve: could not find `Step` in `rusqlite`
   --> src/contact.rs:620:56
    |
620 |         if stmt.as_mut().unwrap().step()? != rusqlite::Step::Done {
    |                                                        ^^^^ could not find `Step` in `rusqlite`
    |
help: consider importing one of these items
    |
4   + use core::iter::Step;
    |
4   + use std::iter::Step;
    |
help: if you import `Step`, refer to it directly
    |
620 -         if stmt.as_mut().unwrap().step()? != rusqlite::Step::Done {
620 +         if stmt.as_mut().unwrap().step()? != Step::Done {
    |

error[E0425]: cannot find value `new_blocking` in this scope
   --> src/contact.rs:627:71
    |
627 |         stmt.as_mut().unwrap().bind(&[rusqlite::types::ToSql::to_sql(&new_blocking)?])?;
    |                                                                       ^^^^^^^^^^^^ not found in this scope
...
654 | fn new_blocking() -> i32 {
    |    ------------ an associated function by that name is available on `Self` here

error[E0425]: cannot find value `DC_CHAT_TYPE_SINGLE` in this scope
   --> src/contact.rs:628:71
    |
628 |         stmt.as_mut().unwrap().bind(&[rusqlite::types::ToSql::to_sql(&DC_CHAT_TYPE_SINGLE)?])?;
    |                                                                       ^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0433]: failed to resolve: could not find `Step` in `rusqlite`
   --> src/contact.rs:630:56
    |
630 |         if stmt.as_mut().unwrap().step()? != rusqlite::Step::Done {
    |                                                        ^^^^ could not find `Step` in `rusqlite`
    |
help: consider importing one of these items
    |
4   + use core::iter::Step;
    |
4   + use std::iter::Step;
    |
help: if you import `Step`, refer to it directly
    |
630 -         if stmt.as_mut().unwrap().step()? != rusqlite::Step::Done {
630 +         if stmt.as_mut().unwrap().step()? != Step::Done {
    |

error[E0425]: cannot find value `DC_EVENT_CONTACTS_CHANGED` in this scope
   --> src/contact.rs:640:29
    |
640 |         context.cb(context, DC_EVENT_CONTACTS_CHANGED, 0, 0);
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

warning: unused import: `Result`
  --> src/contact.rs:13:42
   |
13 | use anyhow::{bail, ensure, Context as _, Result};
   |                                          ^^^^^^
   |
note: the lint level is defined here
  --> src/lib.rs:6:5
   |
6  |     unused,
   |     ^^^^^^
   = note: `#[warn(unused_imports)]` implied by `#[warn(unused)]`

warning: unused imports: `ContactAddress`, `VcardContact`
  --> src/contact.rs:19:5
   |
19 |     ContactAddress, VcardContact,
   |     ^^^^^^^^^^^^^^  ^^^^^^^^^^^^

error[E0425]: cannot find function `dc_contact_new` in this scope
   --> src/contact.rs:609:19
    |
609 |     let contact = dc_contact_new(context)?;
    |                   ^^^^^^^^^^^^^^ not found in this scope

error[E0599]: no method named `is_null_or_invalid` found for reference `&context::Context` in the current scope
   --> src/contact.rs:612:16
    |
612 |     if context.is_null_or_invalid() || context.magic != DC_CONTEXT_MAGIC || id <= DC_CONTACT_ID_LAST_SPECIAL {
    |                ^^^^^^^^^^^^^^^^^^ method not found in `&Context`

error[E0609]: no field `magic` on type `&context::Context`
   --> src/contact.rs:612:48
    |
612 |     if context.is_null_or_invalid() || context.magic != DC_CONTEXT_MAGIC || id <= DC_CONTACT_ID_LAST_SPECIAL {
    |                                                ^^^^^ unknown field
    |
    = note: available field is: `inner`
    = note: available fields are: `blobdir`, `sql`, `smeared_timestamp`, `generating_key_mutex`, `oauth2_mutex` ... and 17 others

error[E0425]: cannot find function `goto_cleanup` in this scope
   --> src/contact.rs:613:9
    |
613 |         goto_cleanup();
    |         ^^^^^^^^^^^^ not found in this scope
    |
help: consider using the associated function on `Self`
    |
613 |         Self::goto_cleanup();
    |         ++++++

error[E0425]: cannot find function `dc_contact_load_from_db` in this scope
   --> src/contact.rs:616:8
    |
616 |     if dc_contact_load_from_db(contact, context.sql, id)? && contact.blocked != new_blocking {
    |        ^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `dc_sqlite3_prepare` in this scope
   --> src/contact.rs:617:21
    |
617 |         stmt = Some(dc_sqlite3_prepare(context.sql, "UPDATE contacts SET blocked=? WHERE id=?;")?);
    |                     ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `goto_cleanup` in this scope
   --> src/contact.rs:621:13
    |
621 |             goto_cleanup();
    |             ^^^^^^^^^^^^ not found in this scope
    |
help: consider using the associated function on `Self`
    |
621 |             Self::goto_cleanup();
    |             ++++++

error[E0425]: cannot find function `dc_sqlite3_prepare` in this scope
   --> src/contact.rs:626:21
    |
626 | ...   stmt = Some(dc_sqlite3_prepare(context.sql, "UPDATE chats SET blocked=? WHERE type=? AND id IN (SELECT chat_id FROM chats_contacts ...
    |                   ^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `goto_cleanup` in this scope
   --> src/contact.rs:631:13
    |
631 |             goto_cleanup();
    |             ^^^^^^^^^^^^ not found in this scope
    |
help: consider using the associated function on `Self`
    |
631 |             Self::goto_cleanup();
    |             ++++++

error[E0425]: cannot find function `dc_marknoticed_contact` in this scope
   --> src/contact.rs:634:9
    |
634 |         dc_marknoticed_contact(context, id)?;
    |         ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0599]: no method named `cb` found for reference `&context::Context` in the current scope
   --> src/contact.rs:640:17
    |
640 |         context.cb(context, DC_EVENT_CONTACTS_CHANGED, 0, 0);
    |                 ^^ method not found in `&Context`

error[E0425]: cannot find function `cleanup` in this scope
   --> src/contact.rs:643:5
    |
643 |     cleanup();
    |     ^^^^^^^ not found in this scope
    |
help: consider using the associated function on `Self`
    |
643 |     Self::cleanup();
    |     ++++++

error[E0425]: cannot find function `dc_contact_unref` in this scope
   --> src/contact.rs:644:5
    |
644 |     dc_contact_unref(contact)?;
    |     ^^^^^^^^^^^^^^^^ not found in this scope

Some errors have detailed explanations: E0252, E0425, E0433, E0599, E0609.
For more information about an error, try `rustc --explain E0252`.
warning: `deltachat` (lib) generated 2 warnings
error: could not compile `deltachat` (lib) due to 25 previous errors; 2 warnings emitted
warning: build failed, waiting for other jobs to finish...
warning: `deltachat` (lib test) generated 2 warnings (2 duplicates)
error: could not compile `deltachat` (lib test) due to 25 previous errors; 2 warnings emitted
error: command `/home/k/.rustup/toolchains/1.77.1-x86_64-unknown-linux-gnu/bin/cargo test --no-run --message-format json-render-diagnostics` exited with code 101

